config/routes.rb
Rails.application.routes.draw do
  get  '/'    => 'calumnis#home', :as =>'home'
  get 'signup' => 'calumnis#signup',:as => 'signup'
  get  'login'   => 'calumnis#login',  :as => 'login'
  get  'search'   => 'calumnis#search_core',  :as => 'search'

  get  'create_account'   => 'calumnis#create_account',  :as => 'create_account'

  get 'testprofile' => 'calumnis#testprofile', :as =>'testprofile'
  patch 'testselect' => 'calumnis#testselect', :as => 'testselect'
  get 'autocomplete'=> 'calumnis#autocomplete', :as => 'autocomplete'

  get  'create_mentee'   => 'calumnis#create_mentee',  :as => 'create_mentee'
  get  'profile'   => 'calumnis#profile',  :as => 'profile'
  patch 'profile' => 'calumnis#update_profile', :as =>"update_profile"
  get  'edit_profile'   => 'calumnis#edit_profile',  :as => 'edit_profile'
  get  'upload' => 'calumnis#upload', :as =>'upload'

  get "add_feedback" => 'calumnis#add_feedback', :as => :add_feedback
  post "store_feedback" => 'calumnis#store_feedback', :as => :store_feedback
  get "display_feedback" => 'calumnis#display_feedback', :as => :display_feedback

  root 'calumnis#home'
  get "/auth/google_oauth2/callback" => "auth#google_callback",:as => "google_callback"
  get "/auth/logout" => "auth#logout", :as => 'logout'
  get "edit_error" => 'calumnis#edit_error', :as =>'edit_error'
  
  patch'upload' => 'calumnis#receiveimg', :as =>'receiveimg'
  get 'become_mentor' => 'calumnis#become_mentor', :as =>'become_mentor'

  resources :conversations do
    resources :messages
  end
  get ':url'=> 'calumnis#showprofile', :as =>'showprofile'
 

end

app/controllers/calumnis_controller.rb
class CalumnisController < ApplicationController

#   before_action :get_game_from_session
#   after_action  :store_game_in_session

  include CalumnisHelper
  private

#   def get_game_from_session
#     @game = HangpersonGame.new('')
#     if !session[:game].blank?
#       @game = YAML.load(session[:game])
#     end
#   end

#   def store_game_in_session
#     session[:game] = @game.to_yaml
#   end

  def people_params
    params.require(:people).permit(:username,:lastname, :email, :description, :company, :start_date, :resume, :university, :major, :graduation, :help, :position,:avatar,:graduation_date,:major,:url,:open_advice,:role,:helpability => [])
  end

  public
  def home
    @people= People.select{|p| p.email==cookies[:email]}
    @mentor1= People.select{|p| p.email=="yima@uiuc.edu"}
    @mentor2= People.select{|p| p.email=="woz@gmail.com"}
    @mentor3= People.select{|p| p.email=="2@gmail.com"}
    @mentor4= People.select{|p| p.email=="3@gmail.com"}
  end
  def signup
  end

  def login

  end


  def edit_profile
    # p cookies[:email]
    @people= People.select{|p| p.email==cookies[:email]}
  end

  def upload
    @people= People.select{|p| p.email==cookies[:email]}
  end

  # def receiveimg
  #       @people= People.select{|p| p.email==cookies[:email]}
  #       @people.first.update_attributes(people_params)
  #       @people.first.save
  #       redirect_to profile_path
  # end

  def search_core
    @people = People.select{|p| p.email == cookies[:email]}
    #input params[:search], params[:type]
    #output
    # @search_ret store ret value
    # @nums number of result
    # @type_index, index of num
    # @type, search type
    # @search_key, params[:search]

    # default, display user
    if params[:type] == 'user'
      params[:type] = 'username' 
    end
    @search_key = params[:search]
    @type = params[:type] || 'username'
    @type_index = 0

    @search_result=[]
    @num=[]
    People.search_type.each_with_index do |type,index|
      result=People.search(params[:search], {fields: [type], autocomplete: true, load: false, misspellings: {below: 4}}) 
      @search_result.push(result)
      @num.push(result.total_count)
      if type==@type
        @type_index=index
        @search_ret=Kaminari.paginate_array(result.map{|u| {username:u.username, company:u.company,url:u.url}}).page(params[:page]).per(10)
      end
    end
    # if @type == 'username' then @type = 'user' end
  end

  def become_mentor
     # @people= People.select{|p| p.email==cookies[:email]}
     # @people.first.update_attribute(:role,'mentor')
     # byebug
     redirect_to edit_profile_path(:become_mentor=>1)
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
  def showprofile
    @people= People.select{|p| p.email==cookies[:email]}
    @otheruser= People.select{|p| p.url==params[:url]}
    # if otheruser not exist
    if @otheruser.first.nil? or @otheruser.first.role=="mentee"
      render_404 and return
    end
    # if not login or mentee
    if (not @people.first.nil?) 
      # if login_user=otheruser
      if @people.first.email==@otheruser.first.email
        redirect_to profile_path
      end
    end
  end
  def add_feedback() respond_to do |format|;format.html; format.js; end; end

  def profile

    # check username and password first
    # p params

    # save
    p cookies[:email]
    @people= People.select{|p| p.email==cookies[:email]}
    # p "in profile ",People.find_by(email: cookies[:email])

    # @pwcorrect=People.find_by(username: params[:people][:username], password: params[:people][:password])

    # p @pwcorrect
    # if @pwcorrect
    #   @people=1
    # else
    #   @pwcorrect="Wrong Username or Password"
    #   render :login
    # end
  end

  def create_account
    # use oauth login first

    # check user exists or not
    p "people, ",@people
    ok= People.select{|p| p.email==cookies[:email]}
    # if user exists
    p "this is ok",ok
    if ok.first.nil?
      # add email to database
      @calumni=People.new()
      @calumni.update_attributes(email:cookies[:email],username:cookies[:name],lastname:cookies[:lastname])
      @calumni.update_attribute(:role,'mentee')
      @calumni.update_attribute(:helped_count, 0)
      while
        val=rand(1...100000).to_s
        ok=People.select{|p| p.url==cookies[:name]+"-"+val}
        # unique url
        if ok.first.nil?
          @calumni.update_attribute(:url, cookies[:name]+"-"+val)
          break
        end
      end
      # tmp_params = ActionController::Parameters.new(email:cookies[:email])
      # People.create!(tmp_params)

    end
    # redirect_to home_path
    redirect_to session[:HTTP_REFERER]||home_path
  end
  def create_mentee
  end
  def edit_error
    @people= People.select{|p| p.email==cookies[:email]}
  end
  def update_profile
    if people_params[:avatar]
      if people_params[:avatar].size >5.megabytes
        redirect_to edit_error_path and return
      end
      if !["image/jpg","image/jpeg","image/png","image/gif"].include? people_params[:avatar].content_type
        redirect_to edit_error_path and return
      end
    end

    if people_params[:resume]
      if people_params[:resume].size >5.megabytes
        redirect_to edit_error_path and return
      end
      if !["application/pdf"].include? people_params[:resume].content_type
        redirect_to edit_error_path and return
      end
    end
    @people= People.select{|p| p.email==cookies[:email]}
    # if mentee and contain :company
    if @people.first.company.nil?
      if not people_params[:company].nil?
        @people.first.update_attributes(:role=>"mentor")
      end
    end
    @people.first.update_attributes(people_params)
    # @people.first.update_attributes(:helpability=>params[:helps])
    #redirect_to profile_path and return
    redirect_to profile_path and return
  end



  # def create
  #   @movie = Movie.create!(movie_params)
  #   flash[:notice] = "#{@movie.title} was successfully created."
  #   redirect_to movies_path
  # end


#   def show
#     status = @game.check_win_or_lose
#     redirect_to win_game_path if status == :win
#     redirect_to lose_game_path if status == :lose
#   end

#   def guess
#     letter = params[:guess]
#     begin
#       if ! @game.guess(letter[0])
#         flash[:message] = "You have already used that letter."
#       end
#     rescue ArgumentError
#       flash[:message] = "Invalid guess."
#     end
#     redirect_to game_path
#   end

#   def win
#     redirect_to game_path unless @game.check_win_or_lose == :win
#   end

#   def lose
#     redirect_to game_path unless @game.check_win_or_lose == :lose
#   end
  def autocomplete
    field=[]
    case params[:type]
    when "company_search"
      field.push("company")
    when "position_search"
      field.push("position")
    else
      field.push("username")
      field.push("position")
      field.push("company")
    end
    ret_val=[]
    field.each do |fi|
      result=People.search(params[:search], {fields: [fi], autocomplete:true, limit: 6, load: false, misspellings: {below: 5}, }) # p "val ",result.map(&fi.to_sym),result
      hash=result.map{|u| {url:u.url,type:fi,username:u.username,company:u.company,name:u[fi],position:u.position,img:u.avatar,descrip:u.description}}
      ret_val+=hash
    end
    if ret_val.length>5
      lastitem= [{"url":"/search?search="+params[:search], "username":"See all search results", "type":"last", }] 
      ret_val=ret_val[0..4]
      ret_val+=lastitem
    end
    render json:ret_val
  end

  def store_feedback
    @msg=Feedback.new({:feedback=>params[:msg],:email=>"anonymous"})
    if @msg.save
      render :json =>{}
    else
      render :json =>{},:status => 500
    end
  end

end

app/helpers/calumnis_helper.rb
module CalumnisHelper
  def ishomepage
    current_page?('/')
  end
	# def redirect_to_back_or_default(default = root_url)
	#   if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
	#     redirect_to :back
	#   else
	#     redirect_to default
	#   end
	# end
end

app/views/calumnis/_add_feedback.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button","id"=>"close_button"} ×
      %h3#myModalLabel
        %strong Any suggestions?
    .modal-body
      .form-group
        %label.control-label#feedback_msg{:for => "message-text"}
        %textarea#message-text.form-control{:placeholder=>"We cherish every single piece of suggestion.",:rows=>4}

    .modal-footer
      %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
      %button.btn.btn-primary#feedback_sub{:type => "button"} Send
    /   %form.button_to{store_feedback_path, :method => "post"}
    /   %input{:type => "submit", :value => "New"}

  
  

app/views/calumnis/add_feedback.js.erb
$("#modal-window").html("<%= j (render 'add_feedback') %>");

$("#feedback_sub").click(function(e) {
    e.preventDefault();
    $.ajax({
        type: "POST",
        url: "/store_feedback",
        data: { 
            msg: $("#message-text").val(), 
        },
        success: function(result) {
            // alert('ok');
            $("#close_button").click();
        },
        error: function(result) {
            console.log("server connection error");
        }
    });
});

app/views/calumnis/create_mentee.html.haml
%h2 haven't implemented

app/views/calumnis/create_mentor.html.haml
%h2 Please complete your profile

= form_for @people, url: createandlogin_path, html: { multipart: true} do |form|

   = form.label :people, :username
   = form.text_field :username

   = form.label :people, :description
   = form.text_field :description

   = form.label :people, :company
   = form.text_field :company

   = form.label :people, :start_date
   = form.text_field :start_date

   = form.label :people, :resume
   = form.text_field :resume

   = form.label :people, :university
   = form.text_field :university

   = form.label :people, :major
   = form.text_field :major

   = form.label :people, :graduation
   = form.text_field :graduation

   = form.label :people, :occupation
   = form.select(:occupation, options_for_select([['Software Engineering'],['CEO'],['COO'],['MD'],['CFO'],['CTO']]))

   = form.label :people, :avatar
   = form.file_field :avatar
   = form.submit 'Submit Profile'
/ = form_tag createandlogin_path do

/   = cookies[:email].inspect

/   = label :people, :username, 'Username'
/   = text_field :people, 'username'
/   = label :people, :description, 'Description'
/   = text_field :people, 'description'
/   = label :people, :company, 'Company'
/   = text_field :people, 'company'
/   = label :people, :start_date, 'Start Date'
/   = text_field :people, 'start_date'
/   = label :people, :resume, 'Resume'
/   = text_field :people, 'resume'
/   = label :people, :university, 'University'
/   = text_field :people, 'university'
/   = label :people, :major, 'Major'
/   = text_field :people, 'major'
/   = label :people, :graduation, 'Graduation Year'
/   = text_field :people, 'graduation'
/   = submit_tag 'Submit Profile'

app/views/calumnis/edit_error.html.haml
%h1 Error the avatar should be jpg,jpeg,png,gif file and must be less than 5 megabytes. The resume should be pdf file and must be less than 5 megabytes.

= link_to 'Go back to profile', profile_path

= link_to 'Go back to edit profile', edit_profile_path

app/views/calumnis/edit_profile.html.haml
/ image, username, major, graduation data, prior work experience, options
-# edit portrait
-# username
-# major
-# graduation data
-# prior work experience


.container
  .row
    = bootstrap_form_for(@people,url: update_profile_path) do |f|
      = f.file_field :avatar
      = f.text_area :description
      = f.select(:major, options_for_select([['EECS'],['CS'],['BIO'],['Biology']]))
      
      = f.date_field :start_date
      = f.date_field :graduation_date

      
      - if params[:become_mentor]||@people.first.role=="mentor"
        %hr
        %h4 Mentor information
        %h6 Fill out additional information about yourself and where you work to become a mentor for other UC Berkeley students
        = f.text_field :company, label: "Company", id: "company_search",autocomplete:"off", :required=>"true",:oninvalid=>"this.setCustomValidity('Fill this to become a mentor')",:oninput=>"this.setCustomValidity('')"
        = f.text_field :position,id: "position_search",autocomplete:"off",:required=>"true",:oninvalid=>"this.setCustomValidity('Fill this to become a mentor')",:oninput=>"this.setCustomValidity('')"
        = f.collection_check_boxes :helpability, People.all_helps, :downcase, :downcase,:label=>'Willing to help with' do |cb|
          = cb.label id:"helps_#{cb}" do
            =cb.text

      = f.text_area :open_advice ,label:"General advice"
      = f.file_field :resume

      = f.submit "Update"

app/views/calumnis/home.html.haml
.container
  .row
    .col-md-12
      %br
      %br
      %br
      %h3{:style=>"color:#1AA3C7;"} 
        %strong CALUMNI
      %h3 Get career advice and referrals from UC Berkeley alumni
      .input-group-btn
        = form_tag search_path, :method => 'get', class: 'input-group',:style=>"width:90%;"   do
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search by company or alumni name', id: "nav_search",autocomplete:"off"
          = submit_tag "Search", class: "btn btn-default"
      %br
      %br
      %br
      %br

.container
  .row
    .col-md-12
      %h3.text-center
        %strong COMPANIES
    .col-md-2.mb-5.col-sm-2
      = link_to search_path(:search=>"amazon",:type=>"company") do
        %img{:height => "100", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/company/amazon.jpg",:alt=>"amazon"}/
    .col-md-2.mb-5.col-sm-2
      = link_to search_path(:search=>"google",:type=>"company") do
        %img{:height => "100", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/company/google.png",:alt=>"google"}/
    .col-md-2.mb-5.col-sm-2
      = link_to search_path(:search=>"facebook",:type=>"company") do
        %img{:height => "100", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/company/fb.png",:alt=>"fb"}/
    .col-md-2.mb-5.col-sm-2
      = link_to search_path(:search=>"snapchat",:type=>"company") do
        %img{:height => "100", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/company/snap.png",:alt=>"snapchat"}/
    .col-md-4.mb-5.col-sm-4#right
      %button.btn.btn-default{:type => "button"} See all companies


  %hr


.container
  .row
    .col-md-12
      %h3.text-center
        %strong MENTORS
    .col-md-3.col-sm-3.details
      .panel.panel-default
        .panel-body
          %a.ratio.img-responsive.img-circle{:href => "#{@mentor1.first.url}", :style => "background-image: url(#{@mentor1.first.avatar});"}
        / List group
        %ul.list-group
          %li.list-group-item #{@mentor1.first.username}
          %li.list-group-item #{@mentor1.first.position}
          %li.list-group-item #{@mentor1.first.company}
    .col-md-3.col-sm-3.details
      .panel.panel-default
        .panel-body
          %a.ratio.img-responsive.img-circle{:href => "#{@mentor2.first.url}", :style => "background-image: url(#{@mentor2.first.avatar});"}
        / List group
        %ul.list-group
          %li.list-group-item #{@mentor2.first.username}
          %li.list-group-item #{@mentor2.first.position}
          %li.list-group-item #{@mentor2.first.company}
    .col-md-3.col-sm-3.details
      .panel.panel-default
        .panel-body
          %a.ratio.img-responsive.img-circle#sam{:href => "#{@mentor4.first.url}", :style => "background-image: url(#{@mentor4.first.avatar});"}
        %ul.list-group
          %li.list-group-item #{@mentor4.first.username}
          %li.list-group-item #{@mentor4.first.position}
          %li.list-group-item #{@mentor4.first.company}
    .col-md-3.mb-5.col-sm-3
      %button.btn.btn-default#right_button{:type => "button"} See all alumni
  %hr

app/views/calumnis/login.html.haml
%h1 login page

#{@pwcorrect}


= form_tag profile_path do

  = label :people, :username, 'Username'
  = text_field :people, 'username'

  = label :people, :password, 'Password'
  = text_field :people, 'password'


  = submit_tag 'Login'
  
  

app/views/calumnis/profile.html.haml
.container
  .fb-profile
    %img.fb-image-lg{:align => "left", :alt => "cover example", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/cover/hero.jpg", :width=>"100",:height=>"250"}/
    %img.fb-image-profile.thumbnail{:align => "left", :alt => "Not set avatar yet", :src => @people.first.avatar}/
    .fb-profile-text
      .username #{@people.first.username}
      .edit 
      = link_to 'Edit', edit_profile_path



%div{:class=>"container-fluid", :id=>"Company"}
  %div{:class=>"row"}
    %div{:class=>"container"}
      .col-md-9.col-lg-9
        %table.table.table-user-information
          %tbody
            %tr
              %td Username
              %td #{@people.first.username}
            %tr
              %td Description:
              %td #{@people.first.description}
            
            %tr
              %td Start date:
              %td #{@people.first.start_date}
            %tr
              %td Graduation date:
              %td #{@people.first.graduation_date}
            
            %tr
            - if @people.first.role =='mentor'
              %td Company:
              %td #{@people.first.company}
            %tr
            - if @people.first.role =='mentor'
              %td General advice:
              %td #{@people.first.open_advice}
            %tr
            - if @people.first.role =='mentor'
              %td Position:
              %td #{@people.first.position}
            %tr
            - if @people.first.role =='mentor'
              %td Help with:
              - if not @people.first.helpability.first.nil?
                %td #{@people.first.display_helpability}
            %tr
            - if @people.first.role =='mentor'
              %td Help Count:
              %td #{@people.first.helped_count}

            %tr
              - if @people.first.resume.url != '/resumes/original/missing.png'
                %iframe{:width => 320, :height =>480, :src => @people.first.resume.url, :frameborder =>"0"}
            / %tr
            / - if @people.first.role =='mentee'
            /   = link_to 'BecomeMentor', become_mentor_path

app/views/calumnis/search.html.haml
.container
  .row
    %ul.nav.nav-pills.underline-nav
      - ['user','company','description'].each_with_index do |i,index|
        - if @type==i
          = link_to search_path(:search=>params[:search],:type=>i), class: "underline-nav-item selected" do
            #{i.titleize}
            %span.Counter.ml-2 #{@num[index]}
        - else
          = link_to search_path(:search=>params[:search],:type=>i), class: "underline-nav-item" do
            #{i.titleize}
            %span.Counter.ml-2 #{@num[index]}
    - if @num[@type_index]==0
      %h2.left #{@num[@type_index]} result about "#{@search_key}"
    - else
      %h2.left #{@num[@type_index]} results about "#{@search_key}"
  %hr
    - if @num[@type_index]!=0
      - @search_ret.each do |i|
        %li.list-group-item 
          %a{:href => "#{i.username}"} #{i.username}  
          %br
          Company: #{i.company}
        %hr

app/views/calumnis/search_core.html.haml
.container
  .row
    %ul.nav.nav-pills.underline-nav
      - People.search_type.each_with_index do |i,index|
        - if @type==i
          = link_to search_path(:search=>params[:search],:type=>i), class: "underline-nav-item selected" do
            #{i.titleize}
            %span.Counter.ml-2 #{@num[index]}
        - else
          = link_to search_path(:search=>params[:search],:type=>i), class: "underline-nav-item" do
            #{i.titleize}
            %span.Counter.ml-2 #{@num[index]}

    - if @num[@type_index]==0
      %h2.left #{@num[@type_index]} result about "#{@search_key}"
    - else
      %h2.left #{@num[@type_index]} results about "#{@search_key}"
  %hr
    - if @num[@type_index]!=0
      - @search_ret.each do |i|
        %li.list-group-item 
          %a{:href => "#{i[:url]}"} #{i[:username]}  
          %br
          Company: #{i[:company]}
        %hr
    = paginate @search_ret

app/views/calumnis/showprofile.html.haml
.container
  .row
    .fb-profile
      %img.fb-image-lg{:align => "left", :alt => "cover example", :src => "https://s3.us-east-2.amazonaws.com/calumni-cs169/cover/hero.jpg", :width=>"100",:height=>"150"}/
      %img.fb-image-profile.thumbnail{:align => "left", :alt => "Not set avatar yet", :src => @otheruser.first.avatar}/
      .fb-profile-text
        .username #{@otheruser.first.username}
        .edit 
          = link_to 'Message Me!', conversations_path(sender_id: current_user, recipient_id: @otheruser.first.id), method: 'post'

%br/

.container
  .row
    .col-sm-8
      .panel.panel-default
        .panel-heading
          Description:
        .panel-body
          #{@otheruser.first.description}
      .panel.panel-default
        .panel-heading
          General advice:
        .panel-body
          - if not @otheruser.first.open_advice.nil?
            %td #{@otheruser.first.open_advice}

    .col-sm-4
      %ul.list-group
        %li.list-group-item Profile
        %li.list-group-item.text-right
          %span.pull-left
            %strong Company
          #{@otheruser.first.company}
        %li.list-group-item.text-right
          %span.pull-left
            %strong Position
          #{@otheruser.first.position}
        %li.list-group-item.text-right
          %span.pull-left
            %strong Help with
          - if not @otheruser.first.helpability.first.nil?
            #{@otheruser.first.display_helpability}
          - else
            &#8203
        %li.list-group-item.text-right
          %span.pull-left
            %strong Start date
          #{@otheruser.first.start_date}&#8203
      %ul.list-group
        %li.list-group-item.text-muted
          Activity
          %i.fa.fa-dashboard.fa-1x
        %li.list-group-item.text-right
          %span.pull-left
            %strong Help Count
          #{@otheruser.first.helped_count}&#8203

app/views/calumnis/signup.html.haml
%h1 Decision Role Page
%h2 Role

.container
  .row
    %h1.left
      = link_to 'Mentor',create_mentor_path
    %h1.left
      = link_to 'Mentee',create_mentee_path

app/views/calumnis/upload.html.haml
= form_for @people, url: receiveimg_path,html: { multipart: true} do |form|
   = form.label :people, :avatar
   = form.file_field :avatar
   = form.submit 'Submit Avatar'