config/routes.rb
Rails.application.routes.draw do
  get  '/'    => 'calumnis#home', :as =>'home'
  get 'signup' => 'calumnis#signup',:as => 'signup'
  get  'login'   => 'calumnis#login',  :as => 'login'
  get  'search'   => 'calumnis#search_core',  :as => 'search'

  get  'create_account'   => 'calumnis#create_account',  :as => 'create_account'

  get 'testprofile' => 'calumnis#testprofile', :as =>'testprofile'
  patch 'testselect' => 'calumnis#testselect', :as => 'testselect'
  get 'autocomplete'=> 'calumnis#autocomplete', :as => 'autocomplete'

  get  'create_mentee'   => 'calumnis#create_mentee',  :as => 'create_mentee'
  get  'profile'   => 'calumnis#profile',  :as => 'profile'
  patch 'profile' => 'calumnis#update_profile', :as =>"update_profile"
  get  'edit_profile'   => 'calumnis#edit_profile',  :as => 'edit_profile'
  get  'upload' => 'calumnis#upload', :as =>'upload'

  get "add_feedback" => 'calumnis#add_feedback', :as => :add_feedback
  post "store_feedback" => 'calumnis#store_feedback', :as => :store_feedback
  get "display_feedback" => 'calumnis#display_feedback', :as => :display_feedback

  root 'calumnis#home'
  get "/auth/google_oauth2/callback" => "auth#google_callback",:as => "google_callback"
  get "/auth/logout" => "auth#logout", :as => 'logout'
  get "edit_error" => 'calumnis#edit_error', :as =>'edit_error'
  
  patch'upload' => 'calumnis#receiveimg', :as =>'receiveimg'
  get 'become_mentor' => 'calumnis#become_mentor', :as =>'become_mentor'

  resources :conversations do
    resources :messages
  end
  get ':url'=> 'calumnis#showprofile', :as =>'showprofile'
 

end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©Calumni
    <br>Powered by <a href="#" target=_new>CS169 Group16</a>
  </p>
</footer>

app/views/common/_navbar.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Calumni", home_path, id: "logo"
    - if not ishomepage
      .input-group-btn.navbar-form.navbar-left
        = form_tag search_path, :method => 'get', class: 'input-group'   do
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Name, Company ', id: "nav_search",autocomplete:"off", size:35
          = submit_tag "Search", class: "btn btn-default"

    %ul.nav.navbar-nav.navbar-right
      - if cookies[:email]
        - if @people.first.role =='mentee'
          %li= link_to "Become a mentor", become_mentor_path
      %li= link_to "Home",   home_path
      - if cookies[:email]
        %li= link_to "Mailbox",conversations_path
      - if not cookies[:email]
        %li= link_to "Log in", create_account_path
      - else
        / display dropdown
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = cookies[:firstname]
            %span.caret
          %ul.dropdown-menu
            %li= link_to "Profile",profile_path
            %li.divider{:role => "separator"}
            %li= link_to 'Feedback', add_feedback_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}
            %li= link_to "Logout",logout_path

#modal-window.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog","tabindex"=>"-1"}





/ = form_tag search_path, :method => 'get', class: 'input-group'   do
/   = text_field_tag :query, params[:query], class: 'form-control typeahead', placeholder: 'Name, Company ', id: "username_search",autocomplete:"off"
/   = submit_tag "Search", class: "btn btn-default"
/ %input.typeahead.form-control#username_search{:placeholder => "States of USA", :type => "text"}/
/ .container
/   .row
/     .input-group.col-sm-3
/       %input#typeahead#username_search.form-control{:type => "text"}/
/       %span.input-group-addon #